### PR TITLE
Update flask_pusher.py

### PR DESCRIPTION
**Pull request by ScriptProdigy**
Added SSL config option.

### CODE REVIEW

**Comment by iurisilvio** [comment]
Thanks for your contribution! Definitelly it's a good thing to add, but breaks `pusher<1.0`.

You must check `__v1__` variable and add the `ssl` configuration to `pusher_kwargs`.

**Comment by ScriptProdigy** [comment]
Ah, good catch, pushed another patch here

**Comment by iurisilvio** [comment]
Great! Thanks! :cake:

**Comment by ScriptProdigy** [comment]
Mind doing a release? I use this with pip, doesn't pull the latest commits, only releases I believe.

**Comment by iurisilvio** [comment]
Done!

**Pull request merged**
